services:
  ucp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ucp-php
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - ucp
    environment:
      VITE_DEV_SERVER: "http://localhost:5173"

  ucp-nginx:
    image: nginx:latest
    container_name: ucp-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ucp-app
    networks:
      - ucp

  ucp-mysql:
    image: mysql:8.0
    container_name: ucp-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ucp
      MYSQL_USER: ucp
      MYSQL_PASSWORD: secret
    volumes:
      - ucp_db_data:/var/lib/mysql
    networks:
      - ucp

  ucp-redis:
    image: redis:alpine
    container_name: ucp-redis
    ports:
      - "6379:6379"
    networks:
      - ucp

  ucp-meilisearch:
    image: getmeili/meilisearch:latest
    container_name: ucp-meilisearch
    restart: unless-stopped
    ports:
      - "7700:7700"
    environment:
      MEILI_NO_ANALYTICS: "true"
    networks:
      - ucp

volumes:
  ucp_db_data:

networks:
  ucp:
    driver: bridge
